### ISSUE TITLE
The plugin ignores the bolded words and LaTex

### ISSUE THREAD

**Issue by TaQuangKhoi** [nhanvu327/rem-graph#2]
the bolded words is "2 cực trị dương"
![ignore bolded words](https://user-images.githubusercontent.com/45689286/87687113-8bfc6680-c7af-11ea-8ac4-f787d0277632.png)

LaTex block is following "với"
![ignore LaTex](https://user-images.githubusercontent.com/45689286/87687575-1775f780-c7b0-11ea-9321-6efd1678b91a.png)
Focus on "với" node.

(em mở nhầm repository-giờ mới đúng chổ nè..)

**Comment by nhanvu327** [comment]
The label now contains the latex string as well as bold or highlight text. The content on popup will display latex formulas properly. @TaQuangKhoi . Please confirm and then I will close this issue

**Comment by TaQuangKhoi** [comment]
Ok.. i agree..
