### ISSUE TITLE
Complex graph after refreshing

### ISSUE THREAD

**Issue by TaQuangKhoi** [nhanvu327/rem-graph#3]
After I expanded the parent rem to show the child rem ..
All node of the child rem turn up at one point ..
![image](https://user-images.githubusercontent.com/45689286/87854376-c72ba080-c93b-11ea-8d7c-0645d441d3f0.png)

(video for detail: https://mega.nz/file/WUsh3SqJ#8GuUHzM9aX63TsWzz9eKnZpKBE38kFpnlXtTkzT7Zt0)

**Comment by nhanvu327** [comment]
@TaQuangKhoi  I thought about this, I think we should keep it as is for now. This specific issue looks like a rare case when you expand notes, it won't happen when you add new rem or modify existing rems, and I think keeping nodes positions after refreshing is more important.
